name: Automated Tests

on: pull_request

jobs:
  vitest:
    name: Vitest Tests on Ubuntu
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: "24"

      - name: Install dependencies
        run: npm ci

      - name: Setup Podman Service
        run: |
          systemctl --user start podman.socket
          echo "DOCKER_HOST=unix://$XDG_RUNTIME_DIR/podman/podman.sock" >> $GITHUB_ENV

      - name: Run Tests
        run: npm test
